[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tlab-pptx"
description = "Create PowerPoint files for Takeuchi Lab"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
keywords = []
classifiers = []
dependencies = [
  "pandas~=1.5.1",
  "plotly~=5.11.0",
  "kaleido~=0.2.1, != 0.2.1.post1",
  "python-pptx~=0.6.21",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/wasedatakeuchilab/tlab-pptx"

[project.optional-dependencies]
test = [
  "pytest~=7.2.0",
  "pytest-cov~=4.0.0",
  "pytest-describe~=2.0.1",
  "mypy~=0.971",
  "flake8~=6.0.0",
  "isort~=5.10.1",
  "black~=22.12.0",
  "pandas-stubs~=1.5.1",
]
dev = [
  "pre-commit~=2.20.0",
]
doc = []

[tool.hatch.version]
path = "src/tlab_pptx/__init__.py"

[tool.mypy]
python_version = "3.10"
strict = true

[[tool.mypy.overrides]]
module = [
  "pptx.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=tlab_pptx"
testpaths = ["tests"]
