[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tlab-pptx"
description = "Creates PowerPoint files for Takeuchi Lab"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
# keywords = []
# classifiers = []
dependencies = [
  "pandas~=2.1.0",
  "plotly~=5.16.1",
  "kaleido~=0.2.1, != 0.2.1.post1",
  "python-pptx~=0.6.21",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/wasedatakeuchilab/tlab-pptx"

[project.optional-dependencies]
test = [
  "pytest==7.4.2",
  "pytest-cov==4.1.0",
  "pytest-describe==2.1.0",
  "pytest-mock==3.11.1",
  "mypy==1.5.1",
  "flake8==6.1.0",
  "isort==5.12.0",
  "black==23.7.0",
]
stub = [
  "pandas-stubs~=2.0.1",
]
doc = []

[tool.hatch.version]
path = "src/tlab_pptx/__init__.py"

[tool.hatch.envs.test]
features = ["test", "stub"]

[tool.hatch.envs.test.scripts]
test = "scripts/test.sh {args}"
format = "scripts/format.sh {args}"
lint = "scripts/lint.sh {args}"

[tool.hatch.envs.doc]
features = ["doc"]

[tool.hatch.envs.doc.scripts]

[tool.mypy]
strict = true
sqlite_cache = true

[[tool.mypy.overrides]]
module = [
  "pptx.*",
  "plotly.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=tlab_pptx"
